# Generated by Django 4.1.7 on 2023-04-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='vote_amount',
            field=models.IntegerField(default=0),
        ),
    ]
