# Generated by Django 4.1.7 on 2023-04-01 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0002_voteoption_vote_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteroom',
            name='participant',
            field=models.ManyToManyField(related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
